version: '3'

services:
  discovery:
    image: ${GITLAB_REGISTRY_PATH:-}ase-discovery:latest
    container_name: ase-discovery
    # build: ./backend/eureka-discovery-service
    ports:
      - "9001:9001"
    working_dir: /opt/app

  gateway:
    image: ${GITLAB_REGISTRY_PATH:-}ase-gateway:latest
    # build: ./backend/gateway
    ports:
      - "9000:9000"
    working_dir: /opt/app
    environment:
      - EUREKA_SERVER=discovery
    depends_on:
      - discovery

  usermngmt:
    image: ${GITLAB_REGISTRY_PATH:-}ase-usermngmt:latest
    container_name: ase-usermngmt
    # build: ./backend/usermngmt
    # restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - "9004:9004"
    working_dir: /opt/app
    environment:
      - EUREKA_SERVER=discovery
      - MONGO_DB_HOSTNAME=mongo
      #- MONGO_DB_USERNAME=aseAdmin
      #- MONGO_DB_PASSWORD=ase
      - KEYSTORE_PATH=./ase_project.keystore
    depends_on:
      - discovery
      - gateway
      - mongo

  boxmanagement:
    image: ${GITLAB_REGISTRY_PATH:-}ase-boxmanagement:latest
    # build: ./backend/boxmanagement
    # restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - "9002:9002"
    working_dir: /opt/app
    environment:
      - EUREKA_SERVER=discovery
      - MONGO_DB_HOSTNAME=mongo
      - PUBLIC_KEY_PATH=./public.key
    depends_on:
      - discovery
      - gateway
      - mongo
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  deliverymanagement:
    image: ${GITLAB_REGISTRY_PATH:-}ase-deliverymanagement:latest
    container_name: ase-deliverymanagement
    # build: ./backend/deliverymanagement
    # restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - "9003:9003"
    working_dir: /opt/app
    environment:
      - EUREKA_SERVER=discovery
      - MONGO_DB_HOSTNAME=mongo
      #- MONGO_DB_USERNAME=aseAdmin
      #- MONGO_DB_PASSWORD=ase
      - PUBLIC_KEY_PATH=./public.key
    depends_on:
      - discovery
      - gateway
      - mongo

  emailnotification:
    image: ${GITLAB_REGISTRY_PATH:-}ase-emailnotification:latest
    container_name: ase-emailnotification
    # build: ./backend/emailnotification
    # restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - "9005:9005"
      - "587:587"
    working_dir: /opt/app
    environment:
      - EUREKA_SERVER=discovery
      - MONGO_DB_HOSTNAME=mongo
      #- MONGO_DB_USERNAME=aseAdmin
      #- MONGO_DB_PASSWORD=ase
      - PUBLIC_KEY_PATH=./public.key
    depends_on:
      - discovery
      - gateway
      - mongo


    
  frontend:
    image: ${GITLAB_REGISTRY_PATH:-}ase-frontend:latest
    depends_on:
      - discovery
      - gateway
      - mongo
      - usermngmt
      - boxmanagement
      - deliverymanagement
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOSTNAME=springboot

  mongo:
    image: mongo
    container_name: mongo
    #environment:
    #  - MONGO_INITDB_DATABASE=userManagement
    ports:
      - "27017:27017"
    volumes:
      - ./ase-mongo4-noauth:/data/db # Up to the : you can change it, what comes afterwards is kinda standard
    #command: [--auth]
    restart: always

