spring:
  application:
    name: emailnotification
  mail:
      protocol: smtp
      host: smtp.gmail.com
      port: 587
      username: ASEDelivering@gmail.com
      password: lhoeoixigpovxvvn
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

server:
  port: 9005

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    edu:
      tum:
        ase: DEBUG
    root: DEBUG
