server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: deliverymanagement
          uri: lb://boxmanagement
          predicates:
            - Path=/deliverymanagement/**
        - id: boxmanagement
          uri: lb://boxmanagement
          predicates:
            - Path=/boxmanagement/**
        - id: usermanagement
          uri: lb://usermanagement
          predicates:
            - Path=/usermanagement/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway

logging:
  level:
    edu:
      tum:
        ase: DEBUG
    root: DEBUG
