server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: deliverymanagement
          uri: lb://DELIVERYMANAGEMENT
          predicates:
            - Path=/deliverymanagement/**

logging:
  level:
    edu:
      tum:
        ase: DEBUG
    root: DEBUG
