spring:
  application:
    name: eureka-discovery-service

server:
  port: 9001

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

logging:
  level:
    edu:
      tum:
        ase: DEBUG
    root: DEBUG
