spring:
  application:
    name: deliverymanagement
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_HOSTNAME:aseAdmin:ase@localhost}:27017/${MONGO_DB_DATABASE:userManagement?authSource=admin} #!172.59.0.14
      # Configure database location
      #host: localhost
      #port: 27017
      #database: deliveryManagement
#
      ## Configure credential
      #username: aseAdmin
      #password: ase
      #authentication-database: admin

      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true

server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:9001/eureka

#logging:
#  level:
#    edu:
#      tum:
#        ase: DEBUG
#    root: DEBUG
