spring:
  application:
    name: boxmanagement
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_HOSTNAME:localhost}:27017/boxManagement
      # Configure database location
      #host: localhost
      #port: 27017
      #database: boxManagement
#
      ## Configure credential
      #username: aseAdmin
      #password: ase
      #authentication-database: admin

      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true

server:
  port: 9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include: health

#logging:
#  level:
#    edu:
#      tum:
#        ase: DEBUG
#    root: DEBUG

#debug: true
