spring:
  application:
    name: boxmanagement
  data:
    mongodb:
      # Configure database location
      host: localhost
      port: 27017
      database: boxManagement

      # Configure credential
      username: aseAdmin
      password: ase
      authentication-database: admin

      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true

server:
  port: 9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    edu:
      tum:
        ase: DEBUG
    root: DEBUG
